import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ReactPlayer from 'react-player'
import React, {useState, useEffect} from 'react'
import Link from 'next/link'


export default function Home(onEnded) {
  const [isShown, setIsShown] = useState(false);
  const hanldeVideoEnded = event => {
    // setIsShown(current => !current);
    setIsShown(true);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Watch2Earn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title}>
          Watch2Earn
        </h1>

        <p className={styles.p}>
          Your current rewards balance is: $$$
        </p>

        <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
        }}>
          <ReactPlayer 
          url='https://www.youtube.com/watch?v=kEOzBqOjWGU'
          onEnded={hanldeVideoEnded}
          />
        </div>

          {
            !isShown && (
              <p className={styles.notRewardedAmount}>Rewarded: $$$</p>
            )
          }

          {
            isShown && (
              <p className={styles.rewardedAmount}>Rewarded: 💰💰💰</p>
            )
          }

          {
            isShown && <Box />
          }
        
        <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
        }}>
        <Link href="/">
          <a className='watch-more-button'> Watch More </a>
        </Link>

        <p></p>

        <Link href="/checkout">
          <a className='checkout-button'> Check Out </a>
        </Link>
        </div>
        <style jsx>{`
          .container {
            justify-content: center;
          }

          .watch-more-button{
            background-color: #0096FF; /* blue */
            border: none;
            color: white;
            padding: 10px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 32px;
            right: 0px;
            width: 225px;
            margin-righ : 100px;
          }

          .checkout-button{
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 10px 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 32px;
            right: 0px;
            width: 225px;
            margin-left: 100px;
          }

          .checkout-button:hover {
            background-color: #73A9AD; 
          }

          .watch-more-button:hover {
            background-color: #187498;
          }

          .reward-balance{
            color: #F9D923;
          }

        `}</style>
    </div>
  )
}
function Box() {
  return (
    <div className="rewardBox">
    </div>
  )
}
